// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDx-CmkGaJ8aM-SqjkOCe2ze8Gc28_6Zs',
    appId: '1:228655714619:web:54fd42a17d152da5c8671e',
    messagingSenderId: '228655714619',
    projectId: 'edutrack-9e0b7',
    authDomain: 'edutrack-9e0b7.firebaseapp.com',
    storageBucket: 'edutrack-9e0b7.firebasestorage.app',
    measurementId: 'G-8ME4NMNPXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB87RdL1A9soybthNiC9-7Us_YAn8kXyAo',
    appId: '1:228655714619:android:ea199c78fdffb6acc8671e',
    messagingSenderId: '228655714619',
    projectId: 'edutrack-9e0b7',
    storageBucket: 'edutrack-9e0b7.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDx-CmkGaJ8aM-SqjkOCe2ze8Gc28_6Zs',
    appId: '1:228655714619:web:127cd0fb56ea9588c8671e',
    messagingSenderId: '228655714619',
    projectId: 'edutrack-9e0b7',
    authDomain: 'edutrack-9e0b7.firebaseapp.com',
    storageBucket: 'edutrack-9e0b7.firebasestorage.app',
    measurementId: 'G-X2G685NVEC',
  );
}
