// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCURS_wrznq9B0eNQWja-5prtfnAoHJkgU',
    appId: '1:361959917095:web:13f50d059a28672ff57002',
    messagingSenderId: '361959917095',
    projectId: 'edutrack-7571b',
    authDomain: 'edutrack-7571b.firebaseapp.com',
    storageBucket: 'edutrack-7571b.firebasestorage.app',
    measurementId: 'G-11HFLKG3Y5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUn_8_Q13Bco-_w1-O7HBkQ14ASlgyy94',
    appId: '1:361959917095:android:9a97a1e20501c207f57002',
    messagingSenderId: '361959917095',
    projectId: 'edutrack-7571b',
    storageBucket: 'edutrack-7571b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf-kFVX6Y7RV4od7Oxnmn52gfAIro_mvo',
    appId: '1:361959917095:ios:a585d64a5dc3f1c7f57002',
    messagingSenderId: '361959917095',
    projectId: 'edutrack-7571b',
    storageBucket: 'edutrack-7571b.firebasestorage.app',
    iosBundleId: 'com.example.edutrackApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf-kFVX6Y7RV4od7Oxnmn52gfAIro_mvo',
    appId: '1:361959917095:ios:a585d64a5dc3f1c7f57002',
    messagingSenderId: '361959917095',
    projectId: 'edutrack-7571b',
    storageBucket: 'edutrack-7571b.firebasestorage.app',
    iosBundleId: 'com.example.edutrackApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCURS_wrznq9B0eNQWja-5prtfnAoHJkgU',
    appId: '1:361959917095:web:d3fb9ab003f455c3f57002',
    messagingSenderId: '361959917095',
    projectId: 'edutrack-7571b',
    authDomain: 'edutrack-7571b.firebaseapp.com',
    storageBucket: 'edutrack-7571b.firebasestorage.app',
    measurementId: 'G-JZWD1YWWGR',
  );
}
