// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIwK-EXl-Xl3C-DvPBl_KIly5GQTexyJo',
    appId: '1:578215553352:android:46456c84d9a71af76cab7d',
    messagingSenderId: '578215553352',
    projectId: 'edutrack-coba',
    storageBucket: 'edutrack-coba.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCje4OyTf8NyV992D4i7-BivasQF_j41LY',
    appId: '1:908631189184:web:618b23c2cb6b8f212d2f25',
    messagingSenderId: '908631189184',
    projectId: 'edutrack-d716c',
    authDomain: 'edutrack-d716c.firebaseapp.com',
    storageBucket: 'edutrack-d716c.firebasestorage.app',
    measurementId: 'G-XELX4ZPWCF',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_bg1fhvFGoeME-c_tpMePIjpiVW_zHK8',
    appId: '1:908631189184:ios:90d6be293f7b5e102d2f25',
    messagingSenderId: '908631189184',
    projectId: 'edutrack-d716c',
    storageBucket: 'edutrack-d716c.firebasestorage.app',
    iosBundleId: 'com.example.edutrackApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_bg1fhvFGoeME-c_tpMePIjpiVW_zHK8',
    appId: '1:908631189184:ios:90d6be293f7b5e102d2f25',
    messagingSenderId: '908631189184',
    projectId: 'edutrack-d716c',
    storageBucket: 'edutrack-d716c.firebasestorage.app',
    iosBundleId: 'com.example.edutrackApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCje4OyTf8NyV992D4i7-BivasQF_j41LY',
    appId: '1:908631189184:web:753180e89dd8922d2d2f25',
    messagingSenderId: '908631189184',
    projectId: 'edutrack-d716c',
    authDomain: 'edutrack-d716c.firebaseapp.com',
    storageBucket: 'edutrack-d716c.firebasestorage.app',
    measurementId: 'G-ZC4KRJ3B0P',
  );

}